"""add alarm category and resolved_at

Revision ID: 49aa7a8ee6ed
Revises: 604a99e800a0
Create Date: 2026-07-04 22:13:14.224596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49aa7a8ee6ed'
down_revision: Union[str, Sequence[str], None] = '604a99e800a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills any existing rows (tables are empty today,
    # but not guaranteed to stay that way by the time this runs elsewhere).
    op.add_column('alert_events', sa.Column('category', sa.String(length=32), nullable=False, server_default='Inne'))
    op.add_column('alert_events', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alert_rules', sa.Column('category', sa.String(length=32), nullable=False, server_default='Inne'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_rules', 'category')
    op.drop_column('alert_events', 'resolved_at')
    op.drop_column('alert_events', 'category')
    # ### end Alembic commands ###
