"""add sensor calibration offset

Revision ID: 604a99e800a0
Revises: 160de95a877e
Create Date: 2026-07-04 21:50:46.543706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604a99e800a0'
down_revision: Union[str, Sequence[str], None] = '160de95a877e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; table is not guaranteed empty.
    op.add_column('sensors', sa.Column('calibration_offset', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'calibration_offset')
    # ### end Alembic commands ###
